# Generated by Django 6.0.5 on 2026-05-10 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembership_internal_role_clubmembership_status'),
        ('users', '0003_alter_user_managers_user_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPortalCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_credentials', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_portal_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club Portal Credential',
                'verbose_name_plural': 'Club Portal Credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
