# Generated by Codex on 2026-05-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembership_internal_role_clubmembership_status'),
        ('events', '0003_alter_event_options_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.club'),
        ),
    ]
