# Generated by Django 5.2.14 on 2026-05-09 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('MEMBER JOINED', 'Member Joined'), ('MEMBER LEFT', 'Member Left'), ('MEMBER KICKED', 'Member Kicked'), ('MEMBER BANNED', 'Member Banned'), ('INVITE ACCEPTED', 'Invite Accepted'), ('ROLE ASSIGNED', 'Role Assigned'), ('ROLE CHANGED', 'Role Changed'), ('CLUB UPDATED', 'Club Updated'), ('CLUB SETTING CHANGED', 'Club Setting Changed'), ('USER LOGIN', 'User Login'), ('USER LOGOUT', 'User Logout'), ('USER PROFILE UPDATED', 'User Profile Updated')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
