# Generated by Django 5.2.14 on 2026-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='internal_role',
            field=models.CharField(default='member', max_length=50),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('approved', 'Approved'), ('banned', 'Banned'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
