# Generated by Django 6.0.5 on 2026-05-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembership_internal_role_clubmembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/thumbnails/'),
        ),
    ]
