# Generated by Django 5.2.14 on 2026-05-09 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('CLUB CREATION', 'Club Creation'), ('CLAIM', 'Claim'), ('ADMINISTRATIVE', 'Administrative'), ('LOGISTICS', 'Logistics')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TREATED', 'Treated'), ('REJECTED', 'Rejected'), ('IN PROGRESS', 'In Progress')], default='PENDING', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
